### ISSUE TITLE
brambolt-rt can't be located in the gradle pluigin repos

### ISSUE THREAD

**Issue by amorozov** [brambolt/gradle-patching#1]
After applying

    plugins {
       id("com.brambolt.gradle.patching")
    }

for versions 2020.12.09-4296 and 2020.12.11-4297 I've got the following error:
  > Could not find com.brambolt:brambolt-rt:2020.12.09-4296.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/brambolt/brambolt-rt/2020.12.09-4296/brambolt-rt-2020.12.09-4296.pom
       - https://repo.maven.apache.org/maven2/com/brambolt/brambolt-rt/2020.12.09-4296/brambolt-rt-2020.12.09-4296.pom
     Required by:
         project :api > com.brambolt.gradle.patching:com.brambolt.gradle.patching.gradle.plugin:2020.12.09-4296 > com.brambolt.gradle:brambolt-gradle-patching:2020.12.09-4296
   > Could not find com.brambolt.gradle:brambolt-gradle-rt:2020.12.09-4296.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/brambolt/gradle/brambolt-gradle-rt/2020.12.09-4296/brambolt-gradle-rt-2020.12.09-4296.pom
       - https://repo.maven.apache.org/maven2/com/brambolt/gradle/brambolt-gradle-rt/2020.12.09-4296/brambolt-gradle-rt-2020.12.09-4296.pom
     Required by:
         project :api > com.brambolt.gradle.patching:com.brambolt.gradle.patching.gradle.plugin:2020.12.09-4296 > com.brambolt.gradle:brambolt-gradle-patching:2020.12.09-4296

Likely, brambolt-rt hasn't been uploaded to Gradle Plugins Central.

**Comment by brambolt** [comment]
Hi Alexey, 

Thanks for the heads-up. These libs are on Bintray at 

- https://bintray.com/brambolt/public/brambolt-rt
- https://bintray.com/brambolt/public/brambolt-gradle-rt

You should be able to build with a repositories list similar to this:

```
 repositories {
    mavenLocal()
    gradlePluginPortal()
    maven { url 'https://dl.bintray.com/brambolt/public' }
  }
```

I've made a note to update the plugin readmes to mention that Bintray needs to be included in the repositories list, and change the samples.

**Comment by brambolt** [comment]
The libraries were migrated to Maven Central after JCenter closed down. 

To use the plugins, make sure mavenCentral() is invoked in (1) the settings.gradle plugin management repositories block, or (2) the build script repositories block of a build.gradle file.

Closing this issue.
